### ISSUE TITLE
Алису запретили в Европе.

### ISSUE THREAD

**Issue by suprimex** [munrexio/yandex2mqtt#13]
Больше немогу использовать этот "мост"...  Официальный ответ Яндекса "Теперь приложение работает в европейских странах, но некоторые функции временно отключены, так как пока не поддерживаются в этих странах. "

**Comment by dredkin** [comment]
Попробуйте использовать прокси через TOR, в нем можно настроить Exit Node на любой список стран.

**Comment by dredkin** [comment]
Ну или VPN, если есть деньги.

**Comment by utya** [comment]
@dredkin а можно попродробней, у сервиса должен быть ip российский или у колонки c алисой?

**Comment by dredkin** [comment]
> @dredkin а можно попродробней, у сервиса должен быть ip российский или у колонки c алисой?

Честно говоря не знаю, у меня все IP Российские, это больше к @suprimex вопрос...

**Comment by suprimex** [comment]
спустя примерно пол-года "разрешили" опять, всё работает как раньше.
