### ISSUE TITLE
Возможно ли отправлять в mqtt топики значения ON и OFF вместо 1 и 0

### ISSUE THREAD

**Issue by alex1iam** [munrexio/yandex2mqtt#14]
Привет
Столкнулся с такой ситуацией - в топики для выключателей приходят значения 0 и 1, а для работы с некоторыми другими проектами требуется ON и OFF. Как можно исправить или дополнить эту ситуацию в проекте yandex2mqtt?

**Comment by alex1iam** [comment]
Решил эту проблему

**Comment by redspirit** [comment]
> Решил эту проблему

Можно ли узнать как вы это решили? Тоже 1/0 получаю, а надо on/off а в настройках как поменять не наблюдаю

**Comment by alex1iam** [comment]
Сори, давно эту почту не проверялправка в yandex2mqtt файла /mnt/data/root/yandex2mqtt/device.js. Нужно в switch в кейсе «on» заменить значения int = val? на 'on': 'off' вместо '1': '0'. 28.12.2020, 00:57, "Alexey" <notifications@github.com>:

Решил эту проблему

Можно ли узнать как вы это решили? Тоже 1/0 получаю, а надо on/off а в настройках как поменять не наблюдаю
